Repository openucx/ucc, pull requests merged in 2021-04, with the labels that each got.

#128 TL: Fix assert condition
  src/components/tl/ucp/tl_ucp_coll.c
Labels: Ready-for-Review

#125 CORE: Add Multi-threaded context progress queue
  src/Makefile.am
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/ucp/tl_ucp_context.c
  src/core/ucc_context.h
  src/core/ucc_progress_queue.c
  src/core/ucc_progress_queue_mt.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/utils/ucc_atomic.h
  src/utils/ucc_compiler_def.h
  src/utils/ucc_datastruct.h
  src/utils/ucc_list.h
  src/utils/ucc_mpool.c
  src/utils/ucc_mpool.h
  src/utils/ucc_parser.h
  src/utils/ucc_spinlock.h
  test/mpi/main.cc
  test/mpi/test_mpi.cc
  test/mpi/test_mpi.h
Labels: Ready-for-Review

#123 MC/CUDA: stream task kernel
  src/components/mc/cuda/kernel/Makefile.am
  src/components/mc/cuda/kernel/mc_cuda_wait_kernel.cu
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
Labels: Ready-for-Review

#116 BUILD: Add news file
  NEWS
Labels: Ready-for-Review

#131 CORE: get lib attr implementation
  src/core/ucc_lib.c
Labels: Ready-for-Review

#132 MC/CUDA: fix parser segv
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
Labels: Ready-for-Review

#133 UTIL: mpool thread mode fix
  src/utils/ucc_mpool.c
Labels: Ready-for-Review

#134 CORE: set default task type
  src/schedule/ucc_schedule.c
Labels: Ready-for-Review

#135 TL/NCCL: fix allreduce type check
  src/components/tl/nccl/tl_nccl_coll.c
Labels: Ready-for-Review

#136 MC/CUDA: Option for non-blocking stream task.
  src/components/mc/cuda/kernel/mc_cuda_wait_kernel.cu
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
  src/components/tl/ucp/tl_ucp_coll.c
Labels: Blocker-for-rel-branch, Ready-for-Review

#139 CORE: Option to disable lock free MT queue
  src/core/ucc_context.c
  src/core/ucc_context.h
  src/core/ucc_progress_queue.c
  src/core/ucc_progress_queue.h
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
Labels: Blocker-for-rel-branch

#137 MC/CUDA: wait for ack from cuda wait task
  src/components/mc/cuda/kernel/mc_cuda_wait_kernel.cu
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
Labels: Blocker-for-rel-branch, Ready-for-Review

#119 TL/CL priority/score selection
  src/Makefile.am
  src/coll_score/ucc_coll_score.c
  src/coll_score/ucc_coll_score.h
  src/coll_score/ucc_coll_score_map.c
  src/components/base/ucc_base_iface.c
  src/components/base/ucc_base_iface.h
  src/components/cl/basic/cl_basic.c
  src/components/cl/basic/cl_basic.h
  src/components/cl/basic/cl_basic_coll.c
  src/components/cl/basic/cl_basic_lib.c
  src/components/cl/basic/cl_basic_team.c
  src/components/cl/ucc_cl.c
  src/components/cl/ucc_cl.h
  src/components/tl/nccl/tl_nccl.c
  src/components/tl/nccl/tl_nccl.h
  src/components/tl/nccl/tl_nccl_team.c
  src/components/tl/ucc_tl.c
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_coll.h
  src/components/tl/ucp/tl_ucp_team.c
  src/core/ucc_coll.c
  src/core/ucc_constructor.c
  src/core/ucc_lib.c
  src/core/ucc_team.c
  src/core/ucc_team.h
  src/ucc/api/ucc.h
  src/utils/ucc_coll_utils.c
  src/utils/ucc_coll_utils.h
  src/utils/ucc_compiler_def.h
  src/utils/ucc_component.c
  src/utils/ucc_component.h
  src/utils/ucc_datastruct.h
  src/utils/ucc_list.h
  src/utils/ucc_math.h
  src/utils/ucc_string.c
  src/utils/ucc_string.h
  test/gtest/Makefile.am
  test/gtest/coll_score/test_score.cc
  test/gtest/coll_score/test_score.h
  test/gtest/coll_score/test_score_str.cc
  test/gtest/coll_score/test_score_update.cc
  test/gtest/coll_score/test_update_score.cc
  test/gtest/core/test_alltoall.cc
  test/gtest/core/test_alltoallv.cc
  test/gtest/utils/test_string.cc
  tools/info/ucc_info.c
Labels: Blocker-for-rel-branch, Ready-for-Review

#74 API: Changing team destroy semantics from blocking to nonblocking
  src/ucc/api/ucc.h
Labels: Ready-for-Review

#117 DOCS: Update component diagram
  docs/images/ucc_components_v2.graffle
  docs/images/ucc_components_v2.pdf
Labels: Ready-for-Review

#118 DOCS: Updates to README
  README.md
Labels: Ready-for-Review

#141 CORE: ucc_team_destroy nb implementation
  src/core/ucc_team.c
  src/core/ucc_team.h
  test/gtest/common/test_ucc.cc
  test/mpi/test_mpi.cc
Labels: Ready-for-Review

#146 TEST: test mpi oob.participants
  test/mpi/test_mpi.cc
Labels: Ready-for-Review

#148 V0.1.x: TEST: test mpi oob.participants
  test/mpi/test_mpi.cc
Labels: Ready-for-Review, Target: v0.1.x

#121 TEST: mpi: added set CUDA device
  src/components/mc/cuda/kernel/mc_cuda_reduce.cu
  src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
  test/mpi/main.cc
  test/mpi/test_mpi.cc
  test/mpi/test_mpi.h
Labels: Ready-for-Review

#140 Fix linter warnings
  src/coll_score/ucc_coll_score.c
  src/components/cl/basic/cl_basic_team.c
  src/components/mc/cpu/mc_cpu.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_ep.c
  src/core/ucc_ee.c
  src/core/ucc_progress_queue_mt.c
  src/schedule/ucc_schedule.c
Labels: Ready-for-Review

#142 CORE: change COLL_SCORE separator
  src/coll_score/ucc_coll_score.c
  src/components/base/ucc_base_iface.c
  test/gtest/coll_score/test_score_str.cc
Labels: Ready-for-Review, Target: v0.1.x

#153 TL/NCCL: allgather INPLACE fix
  src/components/tl/nccl/tl_nccl_coll.c
Labels: Ready-for-Review, Target: Master, Target: v0.1.x

#155 V0.1.x: TL/NCCL: allgather INPLACE fix
  src/components/tl/nccl/tl_nccl_coll.c
Labels: Ready-for-Review, Target: v0.1.x

#154 V0.1.x: CORE: change SCORE separator
  src/coll_score/ucc_coll_score.c
  src/components/base/ucc_base_iface.c
  test/gtest/coll_score/test_score_str.cc
Labels: Ready-for-Review, Target: v0.1.x

#164 MC/CUDA: check device count
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
  test/mpi/test_mpi.cc
Labels: Ready-for-Review

#150 Enabled extended CI
  .ci/Dockerfile.centos8
  .ci/Jenkinsfile.shlib
  .ci/configs/swx-clx01/hostfile.txt
  .ci/configs/swx-clx02/hostfile.txt
  .ci/job_matrix.yaml
  .ci/patches/dlrm/0001-Added-torch_ucc-support.patch
  .ci/patches/dlrm/0002-Fixed-arg-list.patch
  .ci/proj_jjb.yaml
  .ci/scripts/build_ucc.sh
  .ci/scripts/build_ucx.sh
  .ci/scripts/configure_python.sh
  .ci/scripts/env.sh
  .ci/scripts/install_torch.sh
  .ci/scripts/install_torch_ucc.sh
  .ci/scripts/run_dlrm.sh
  .ci/scripts/run_dlrm_docker.sh
  .ci/scripts/run_dlrm_s_pytorch.sh
  .ci/scripts/run_docker.sh
  .ci/scripts/run_tests_torch_ucc.sh
  .ci/scripts/run_tests_ucc.sh
  .ci/scripts/run_tests_ucc_mpi.sh
  .ci/scripts/run_tests_ucc_mpi_docker.sh
  .ci/scripts/stop_docker.sh
  .gitignore
Labels: Ready-for-Review

#167 CORE: dbg log level for "unsupported"
  src/components/tl/ucp/alltoall/alltoall.c
  src/core/ucc_coll.c
Labels: Ready-for-Review, Target: Master, Target: v0.1.x

#166 TOOLS/PERFTEST: ucc perftest
  Makefile.am
  config/m4/mpi.m4
  configure.ac
  src/utils/ucc_coll_utils.h
  tools/perf/Makefile.am
  tools/perf/ucc_perftest.cc
  tools/perf/ucc_perftest.h
  tools/perf/ucc_pt_benchmark.cc
  tools/perf/ucc_pt_benchmark.h
  tools/perf/ucc_pt_bootstrap.h
  tools/perf/ucc_pt_bootstrap_mpi.cc
  tools/perf/ucc_pt_bootstrap_mpi.h
  tools/perf/ucc_pt_coll.cc
  tools/perf/ucc_pt_coll.h
  tools/perf/ucc_pt_comm.cc
  tools/perf/ucc_pt_comm.h
  tools/perf/ucc_pt_config.cc
  tools/perf/ucc_pt_config.h
Labels: Ready-for-Review

#165 CL/BASIC: fill coll_types attribute
  src/components/cl/basic/cl_basic_lib.c
  src/components/tl/nccl/tl_nccl_lib.c
  src/components/tl/ucp/tl_ucp_lib.c
Labels: Ready-for-Review, Target: v0.1.x

#169 V0.1.x MC/CUDA: check device count
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
Labels: Ready-for-Review, Target: v0.1.x
