Repository openucx/ucc, pull requests merged in 2021-07, with the labels that each got.

#229 MC: check provided thread mode
  config/m4/cuda.m4
  src/components/mc/base/ucc_mc_base.h
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/kernel/Makefile.am
  src/components/mc/cuda/kernel/mc_cuda_reduce.cu
  src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
  src/components/mc/cuda/mc_cuda.c
  src/core/ucc_mc.c
  src/core/ucc_mc.h
  test/gtest/core/test_mc.cc
  test/gtest/core/test_mc_cuda.cc
Labels: Ready-for-Review, Target: v0.1.x, bug

#225 API: Adding details for buffer info
  src/ucc/api/ucc.h
Labels: Ready-for-Review, Target: v0.1.x

#235 Topic/persistent
  src/components/tl/ucp/allgather/allgather_knomial.c
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allgatherv/allgatherv_ring.c
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
  src/components/tl/ucp/alltoall/alltoall.c
  src/components/tl/ucp/alltoall/alltoall.h
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  src/components/tl/ucp/alltoallv/alltoallv.c
  src/components/tl/ucp/alltoallv/alltoallv.h
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/bcast/bcast_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/tl_ucp_coll.h
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  test/gtest/common/test_ucc.cc
  test/gtest/common/test_ucc.h
  test/gtest/core/test_allgather.cc
  test/gtest/core/test_allgatherv.cc
  test/gtest/core/test_allreduce.cc
  test/gtest/core/test_alltoall.cc
  test/gtest/core/test_alltoallv.cc
  test/gtest/core/test_bcast.cc
Labels: Ready-for-Review

#243 TEST/MPI: fixes hangs
  test/mpi/main.cc
  test/mpi/test_allgather.cc
  test/mpi/test_allgatherv.cc
  test/mpi/test_allreduce.cc
  test/mpi/test_alltoall.cc
  test/mpi/test_alltoallv.cc
  test/mpi/test_bcast.cc
  test/mpi/test_mpi.cc
  test/mpi/test_mpi.h
Labels: Ready-for-Review, Target: v0.1.x

#222 TEST: Updated torch_ucc repo, fixed cmake issue
  .ci/Dockerfile.centos8
  .ci/Dockerfile.fedora33
  .ci/job_matrix.yaml
Labels: Ready-for-Review

#249 TL/UCP: skip 0 count in alltoallv
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/tl_ucp_sendrecv.h
  test/gtest/core/test_alltoallv.cc
Labels: Ready-for-Review

#254 TL/NCCL: use memops to check completion
  src/components/tl/nccl/tl_nccl.c
  src/components/tl/nccl/tl_nccl.h
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/nccl/tl_nccl_team.c
Labels: Ready-for-Review

#257 TL/NCCL: fix event leak with memops
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/nccl/tl_nccl_team.c
Labels: Ready-for-Review

#223 TOOLS: added option to print bw in perftest
  tools/perf/ucc_pt_benchmark.cc
  tools/perf/ucc_pt_benchmark.h
  tools/perf/ucc_pt_coll.cc
  tools/perf/ucc_pt_coll.h
  tools/perf/ucc_pt_coll_allgather.cc
  tools/perf/ucc_pt_coll_allgatherv.cc
  tools/perf/ucc_pt_coll_allreduce.cc
  tools/perf/ucc_pt_coll_alltoall.cc
  tools/perf/ucc_pt_coll_alltoallv.cc
  tools/perf/ucc_pt_coll_barrier.cc
  tools/perf/ucc_pt_coll_bcast.cc
  tools/perf/ucc_pt_config.cc
  tools/perf/ucc_pt_config.h
Labels: Ready-for-Review

#255 Add config file for cmake to find UCC on system
  Makefile.am
  cmake/Makefile.am
  cmake/ucc-config-version.cmake.in
  cmake/ucc-config.cmake.in
  cmake/ucc-targets.cmake.in
  configure.ac
Labels: Ready-for-Review

#258 TL/NCCL: change task status from progress only
  src/components/tl/nccl/tl_nccl.h
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_context.c
Labels: Ready-for-Review

#239 SCHEDULE: rework listeners
  .github/workflows/codestyle.yaml
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  test/gtest/Makefile.am
  test/gtest/core/test_schedule.cc
Labels: Ready-for-Review

#260 TL/UCP: triggered post for sra
  src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
Labels: Ready-for-Review

#251 TEST: disable NCCL and GDR
  test/gtest/common/test_ucc.cc
Labels: Ready-for-Review

#265 BUILD: improve cmake support
  .github/workflows/main.yaml
  cmake/ucc-config.cmake.in
  cmake/ucc-targets.cmake.in
  test/cmake/CMakeLists.txt
  test/cmake/main.cpp
Labels: Ready-for-Review

#268 MC: fixed mc reduce multi parameters order
  src/components/mc/base/ucc_mc_base.h
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cpu/reduce/mc_cpu_reduce.h
  src/components/mc/cpu/reduce/mc_cpu_reduce_double.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_float.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int16.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int32.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int64.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int8.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint16.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint32.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint64.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint8.c
  src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
  src/components/mc/cuda/mc_cuda.h
  src/core/ucc_mc.c
  src/core/ucc_mc.h
Labels: Ready-for-Review

#241 Cache args on coll_task
  src/components/tl/nccl/tl_nccl.h
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_team.c
  src/components/tl/ucp/allgather/allgather.c
  src/components/tl/ucp/allgather/allgather_knomial.c
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allgatherv/allgatherv.c
  src/components/tl/ucp/allgatherv/allgatherv_ring.c
  src/components/tl/ucp/allreduce/allreduce.c
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/alltoall/alltoall.c
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  src/components/tl/ucp/alltoallv/alltoallv.c
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/barrier/barrier_knomial.c
  src/components/tl/ucp/bcast/bcast_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_coll.h
  src/components/tl/ucp/tl_ucp_service_coll.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  test/gtest/core/test_schedule.cc
Labels: Ready-for-Review

#277 Enabled UCC unit tests
  .ci/job_matrix.yaml
Labels: Ready-for-Review

#279 Topic/node hash fix
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_ep.c
  src/components/tl/ucp/tl_ucp_ep.h
  src/components/tl/ucp/tl_ucp_ep_hash.h
  src/core/ucc_context.c
  src/core/ucc_context.h
  src/core/ucc_team.h
  src/utils/ucc_proc_info.c
  src/utils/ucc_proc_info.h
Labels: Ready-for-Review, Target: v0.1.x

#267 CORE: coll_init log
  config/m4/configure.m4
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/core/ucc_coll.c
  src/utils/ucc_coll_utils.c
  src/utils/ucc_coll_utils.h
Labels: Ready-for-Review

#281 V0.1.x: Adjust allgather, alltoall count
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  test/gtest/core/test_allgather.cc
  test/gtest/core/test_alltoall.cc
  test/mpi/test_allgather.cc
  test/mpi/test_alltoall.cc
Labels: Ready-for-Review, Target: v0.1.x
