Repository openucx/ucc, pull requests merged in 2021-05, with the labels that each got.

#171 Cleanup build flags
  config/m4/compiler.m4
  configure.ac
  src/Makefile.am
  src/coll_score/ucc_coll_score.c
  src/components/cl/basic/Makefile.am
  src/components/mc/cpu/Makefile.am
  src/components/mc/cuda/Makefile.am
  src/components/mc/cuda/mc_cuda.h
  src/components/tl/nccl/Makefile.am
  src/components/tl/nccl/tl_nccl_team.c
  src/components/tl/ucp/Makefile.am
  src/utils/ucc_class.h
  test/mpi/Makefile.am
  tools/info/Makefile.am
  tools/perf/Makefile.am
Labels: Ready-for-Review

#177 API: completion callback
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allgatherv/allgatherv_ring.c
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/barrier/barrier_knomial.c
  src/components/tl/ucp/bcast/bcast_knomial.c
  src/core/ucc_coll.c
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
  src/schedule/ucc_schedule.h
  src/ucc/api/ucc.h
  src/ucc/api/ucc_def.h
  test/gtest/core/test_barrier.cc
Labels: Ready-for-Review

#178 V0.1.x API: completion callback
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allgatherv/allgatherv_ring.c
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/barrier/barrier_knomial.c
  src/components/tl/ucp/bcast/bcast_knomial.c
  src/core/ucc_coll.c
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
  src/schedule/ucc_schedule.h
  src/ucc/api/ucc.h
  src/ucc/api/ucc_def.h
  test/gtest/core/test_barrier.cc
Labels: Ready-for-Review, Target: v0.1.x

#179 TEST: reduce amount of err output
  test/gtest/common/test.h
  test/gtest/common/test_ucc.h
  test/gtest/core/test_allgather.cc
  test/gtest/core/test_allgatherv.cc
  test/gtest/core/test_allreduce.cc
  test/gtest/core/test_alltoall.cc
  test/gtest/core/test_alltoallv.cc
  test/gtest/core/test_bcast.cc
Labels: Ready-for-Review, Target: Master

#174 CORE: fix memory leaks
  src/coll_score/ucc_coll_score.c
  src/core/ucc_lib.c
  src/core/ucc_team.c
  test/gtest/coll_score/test_score.cc
  test/gtest/coll_score/test_score_str.cc
  test/mpi/test_barrier.cc
Labels: Ready-for-Review

#189 EE: check ee available
  src/components/mc/base/ucc_mc_base.h
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
  src/core/ucc_mc.c
Labels: Ready-for-Review

#192 TEST: return error from UCCProcess constructor
  test/gtest/common/test_ucc.cc
Labels: Ready-for-Review

#190 CORE: remove ucc_tl_type_t
  src/Makefile.am
  src/components/base/ucc_base_iface.h
  src/components/cl/basic/cl_basic_context.c
  src/components/cl/basic/cl_basic_lib.c
  src/components/cl/ucc_cl.c
  src/components/cl/ucc_cl.h
  src/components/tl/ucc_tl.c
  src/components/tl/ucc_tl.h
  src/core/ucc_lib.c
  src/core/ucc_lib.h
  src/core/ucc_team.c
  src/utils/ucc_parser.c
  src/utils/ucc_parser.h
Labels: Ready-for-Review, Target: Master

#191 CL/BASIC: use ALL available TLs by default
  src/components/cl/basic/cl_basic.c
  src/components/cl/basic/cl_basic.h
  src/components/cl/basic/cl_basic_context.c
  src/components/cl/basic/cl_basic_team.c
  src/components/cl/ucc_cl.c
  src/core/ucc_context.c
  src/core/ucc_context.h
  src/utils/ucc_component.c
  src/utils/ucc_component.h
  test/gtest/core/test_context_config.cc
Labels: Ready-for-Review, Target: Master

#161 TL/UCP: SRA knomial allreduce
  src/Makefile.am
  src/coll_patterns/recursive_knomial.h
  src/coll_patterns/sra_knomial.h
  src/coll_score/ucc_coll_score.c
  src/components/base/ucc_base_iface.h
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/allgather/allgather.h
  src/components/tl/ucp/allgather/allgather_knomial.c
  src/components/tl/ucp/allreduce/allreduce.c
  src/components/tl/ucp/allreduce/allreduce.h
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
  src/components/tl/ucp/barrier/barrier_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter.h
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_coll.h
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_lib.c
  src/core/ucc_coll.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/utils/ucc_math.h
Labels: Ready-for-Review, Target: Master

#194 CORE: register ucc ctx config table
  src/core/ucc_context.c
Labels: Ready-for-Review

#160 TL/UCP: knomial allreduce move memory allocation from post to init
  src/components/tl/ucp/allreduce/allreduce.c
  src/components/tl/ucp/allreduce/allreduce.h
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/tl_ucp_service_coll.c
Labels: Ready-for-Review

#173 TOOLS: adding more options to perftest
  tools/perf/Makefile.am
  tools/perf/ucc_perftest.cc
  tools/perf/ucc_perftest.h
  tools/perf/ucc_pt_benchmark.cc
  tools/perf/ucc_pt_benchmark.h
  tools/perf/ucc_pt_bootstrap.h
  tools/perf/ucc_pt_bootstrap_mpi.cc
  tools/perf/ucc_pt_bootstrap_mpi.h
  tools/perf/ucc_pt_coll.cc
  tools/perf/ucc_pt_coll.h
  tools/perf/ucc_pt_coll_allgather.cc
  tools/perf/ucc_pt_coll_allgatherv.cc
  tools/perf/ucc_pt_coll_allreduce.cc
  tools/perf/ucc_pt_coll_alltoall.cc
  tools/perf/ucc_pt_coll_alltoallv.cc
  tools/perf/ucc_pt_coll_barrier.cc
  tools/perf/ucc_pt_coll_bcast.cc
  tools/perf/ucc_pt_comm.cc
  tools/perf/ucc_pt_comm.h
  tools/perf/ucc_pt_config.cc
  tools/perf/ucc_pt_config.h
Labels: Ready-for-Review

#202 CL/BASIC: generalize get_lib_attr
  src/components/cl/basic/cl_basic.h
  src/components/cl/basic/cl_basic_lib.c
Labels: Ready-for-Review

#206 Fix alltoallv test
  test/gtest/core/test_alltoallv.cc
Labels: Ready-for-Review

#193 UCC context address query
  src/components/base/ucc_base_iface.h
  src/components/cl/basic/cl_basic.c
  src/components/cl/basic/cl_basic_context.c
  src/components/cl/basic/cl_basic_lib.c
  src/components/cl/ucc_cl.h
  src/components/tl/nccl/tl_nccl.c
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/nccl/tl_nccl_lib.c
  src/components/tl/ucc_tl.h
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_lib.c
  src/core/ucc_context.c
  src/core/ucc_context.h
  src/ucc/api/ucc.h
  src/ucc/api/ucc_def.h
  src/utils/ucc_component.c
  src/utils/ucc_component.h
  src/utils/ucc_math.h
  test/gtest/core/test_context.cc
  test/gtest/core/test_context.h
Labels: Ready-for-Review

#209 TEST: Fix test_obj_size
  test/gtest/common/test_obj_size.cc
Labels: Ready-for-Review

#205 BUILD: fix building with icc
  config/m4/compiler.m4
  src/coll_score/ucc_coll_score.c
  src/coll_score/ucc_coll_score.h
  src/components/cl/ucc_cl.c
  src/components/mc/cpu/mc_cpu.c
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/ucp/allgatherv/allgatherv_ring.c
  src/core/ucc_context.c
  src/core/ucc_mc.c
  tools/info/ucc_info.c
Labels: Ready-for-Review

#157 UTIL: Add ucc_unlikely
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_team.c
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allgatherv/allgatherv.c
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_ep.c
  src/components/tl/ucp/tl_ucp_ep.h
  src/components/tl/ucp/tl_ucp_sendrecv.h
  src/core/ucc_coll.c
  src/core/ucc_ee.c
  src/core/ucc_mc.c
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/utils/ucc_class.h
  src/utils/ucc_compiler_def.h
  src/utils/ucc_math.h
Labels: Ready-for-Review
