Repository openucx/ucc, pull requests merged in 2021-12, with the labels that each got.

#360 TL/UCP: fix bcast schedule timeout
  src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
  src/components/tl/ucp/bcast/bcast_sag_knomial.c
  src/components/tl/ucp/tl_ucp_coll.h
Labels: bug, Ready-for-Review

#309 TL/UCP: add one-sided collective support
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_sendrecv.h
  src/components/tl/ucp/tl_ucp_team.c
  src/core/ucc_context.c
Labels: Ready-for-Review

#359 TEST: Refactor ci
  .ci/Dockerfile.centos8
  .ci/build_base_docker/Dockerfile.centos8.base
  .ci/build_base_docker/job_matrix.yaml
  .ci/build_base_docker/proj_jjb.yaml
Labels: Ready-for-Review

#323 TL/UCP: One-sided A2A
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/alltoall/alltoall.c
  src/components/tl/ucp/alltoall/alltoall.h
  src/components/tl/ucp/alltoall/alltoall_onesided.c
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_coll.h
Labels: Ready-for-Review

#365 TL/UCP: query supported memory types
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_sendrecv.h
  src/components/tl/ucp/tl_ucp_team.c
Labels: Ready-for-Review

#368 UTIL: fix perftest comm allreduce
  tools/perf/ucc_pt_comm.cc
Labels: Ready-for-Review

#156 TL collective plugin interface
  autogen.sh
  config/m4/tl_coll_plugins.m4
  configure.ac
  src/coll_score/ucc_coll_score.c
  src/coll_score/ucc_coll_score.h
  src/components/base/ucc_base_iface.h
  src/components/tl/ucc_tl.h
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/coll_plugins/example/Makefile.am
  src/components/tl/ucp/coll_plugins/example/configure.m4
  src/components/tl/ucp/coll_plugins/example/example.c
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_coll.h
  src/components/tl/ucp/tl_ucp_lib.c
  src/components/tl/ucp/tl_ucp_team.c
  src/core/ucc_lib.c
Labels: Ready-for-Review, Target: Master

#369 BUILD: gitignore plugins generated makefile
  .gitignore
Labels: Ready-for-Review

#372 BUILD: bump version to 1.1.0
  configure.ac
Labels: Ready-for-Review

#371 UTIL: fix ucs mpool v1.13.x
  src/utils/ucc_mpool.c
Labels: Ready-for-Review

#367 UTIL: ucc cpu arch specific functions
  src/Makefile.am
  src/components/cl/hier/cl_hier_context.c
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/sharp/tl_sharp_context.c
  src/components/tl/ucp/tl_ucp_context.c
  src/utils/arch/aarch64/cpu.h
  src/utils/arch/cpu.h
  src/utils/arch/ppc64/cpu.h
  src/utils/arch/x86_64/cpu.h
  src/utils/ucc_compiler_def.h
Labels: Ready-for-Review

#350 CORE: automatic TLs build discovery
  .gitignore
  autogen.sh
  config/m4/check_tls.m4
  config/m4/nccl.m4
  config/m4/sharp.m4
  configure.ac
  src/Makefile.am
  src/components/tl/nccl/Makefile.am
  src/components/tl/nccl/configure.m4
  src/components/tl/sharp/Makefile.am
  src/components/tl/sharp/configure.m4
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/configure.m4
Labels: Ready-for-Review
