Repository openucx/ucc, pull requests merged in 2021-06, with the labels that each got.

#208 TEST: Fix data_finiliaze in test_bcast
  test/gtest/core/test_bcast.cc
Labels: Ready-for-Review

#211 CORE: bugfix in ucc_task_complete
  src/schedule/ucc_schedule.h
Labels: Ready-for-Review, bug

#213 V0.1.x: TEST: Fix test_obj_size (#209)
  test/gtest/common/test_obj_size.cc
Labels: Ready-for-Review

#212 V0.1.x: CORE: bugfix in ucc_task_complete
  src/schedule/ucc_schedule.h
Labels: Ready-for-Review, bug

#210 CORE: Fix MT progress queue
  src/Makefile.am
  src/core/ucc_progress_queue.h
  src/core/ucc_progress_queue_mt.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/utils/ucc_atomic.h
  src/utils/ucc_lock_free_queue.h
  test/gtest/Makefile.am
  test/gtest/utils/test_lock_free_queue.cc
Labels: Ready-for-Review

#214 TEST: fix ucc allocations
  test/gtest/common/test_ucc.h
  test/gtest/core/test_allgather.cc
  test/gtest/core/test_allgatherv.cc
  test/gtest/core/test_allreduce.cc
  test/gtest/core/test_alltoall.cc
  test/gtest/core/test_alltoallv.cc
  test/gtest/core/test_bcast.cc
  test/mpi/buffer.cc
  test/mpi/test_allgather.cc
  test/mpi/test_allgatherv.cc
  test/mpi/test_allreduce.cc
  test/mpi/test_alltoall.cc
  test/mpi/test_alltoallv.cc
  test/mpi/test_bcast.cc
  test/mpi/test_case.cc
  test/mpi/test_mpi.h
  tools/perf/ucc_perftest.h
  tools/perf/ucc_pt_coll_allgatherv.cc
  tools/perf/ucc_pt_coll_alltoallv.cc
Labels: Ready-for-Review

#207 MC: cleanup interface
  src/components/mc/base/ucc_mc_base.h
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
  src/components/tl/ucp/tl_ucp.c
  src/core/ucc_coll.c
  src/core/ucc_mc.c
  src/core/ucc_mc.h
  test/gtest/core/test_mc_cuda.cc
Labels: Ready-for-Review

#200 MC/CPU: optimized reduce-multi
  src/components/mc/cpu/Makefile.am
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cpu/mc_cpu_reduce.h
  src/components/mc/cpu/reduce/mc_cpu_reduce.h
  src/components/mc/cpu/reduce/mc_cpu_reduce_double.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_float.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int16.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int32.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int64.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int8.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint16.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint32.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint64.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint8.c
Labels: Ready-for-Review

#196 MC: Adding ucc mpool implementation
  src/components/mc/base/ucc_mc_base.h
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cpu/mc_cpu.h
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/tl_ucp_coll.h
  src/core/ucc_lib.c
  src/core/ucc_mc.c
  src/core/ucc_mc.h
  src/utils/ucc_parser.h
  test/gtest/common/test_ucc.h
  test/gtest/core/test_allgather.cc
  test/gtest/core/test_allgatherv.cc
  test/gtest/core/test_allreduce.cc
  test/gtest/core/test_alltoall.cc
  test/gtest/core/test_alltoallv.cc
  test/gtest/core/test_bcast.cc
  test/gtest/core/test_mc.cc
  test/gtest/core/test_mc_cuda.cc
  test/gtest/core/test_mc_reduce.h
  test/mpi/buffer.cc
  test/mpi/test_allgather.cc
  test/mpi/test_allgatherv.cc
  test/mpi/test_allreduce.cc
  test/mpi/test_alltoall.cc
  test/mpi/test_alltoallv.cc
  test/mpi/test_bcast.cc
  test/mpi/test_case.cc
  test/mpi/test_mpi.h
  tools/perf/ucc_pt_coll.h
  tools/perf/ucc_pt_coll_allgather.cc
  tools/perf/ucc_pt_coll_allgatherv.cc
  tools/perf/ucc_pt_coll_allreduce.cc
  tools/perf/ucc_pt_coll_alltoall.cc
  tools/perf/ucc_pt_coll_alltoallv.cc
  tools/perf/ucc_pt_coll_barrier.cc
  tools/perf/ucc_pt_coll_bcast.cc
Labels: Ready-for-Review

#217 MC: save memtype in header
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cuda/mc_cuda.c
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/core/ucc_mc.c
  src/core/ucc_mc.h
  test/gtest/core/test_allgather.cc
  test/gtest/core/test_allgatherv.cc
  test/gtest/core/test_allreduce.cc
  test/gtest/core/test_alltoall.cc
  test/gtest/core/test_alltoallv.cc
  test/gtest/core/test_bcast.cc
  test/gtest/core/test_mc.cc
  test/gtest/core/test_mc_cuda.cc
  test/gtest/core/test_mc_reduce.h
  test/mpi/buffer.cc
  test/mpi/test_case.cc
  tools/perf/ucc_pt_coll_allgather.cc
  tools/perf/ucc_pt_coll_allgatherv.cc
  tools/perf/ucc_pt_coll_allreduce.cc
  tools/perf/ucc_pt_coll_alltoall.cc
  tools/perf/ucc_pt_coll_alltoallv.cc
  tools/perf/ucc_pt_coll_bcast.cc
Labels: Ready-for-Review

#218 MC/CPU: remove unnecessary dt param
  src/components/mc/cpu/mc_cpu.c
  src/components/mc/cpu/reduce/mc_cpu_reduce.h
  src/components/mc/cpu/reduce/mc_cpu_reduce_double.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_float.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int16.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int32.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int64.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_int8.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint16.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint32.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint64.c
  src/components/mc/cpu/reduce/mc_cpu_reduce_uint8.c
Labels: Ready-for-Review

#220 TOOLS: fixing warmup in perftest
  tools/perf/ucc_pt_benchmark.cc
Labels: Ready-for-Review

#216 DOCS: Component diagram update
  docs/images/ucc_components.graffle
  docs/images/ucc_components.pdf
  docs/images/ucc_components.png
Labels: Ready-for-Review

#203 UCC Profile
  config/m4/configure.m4
  configure.ac
  src/Makefile.am
  src/components/tl/ucp/allgather/allgather_knomial.c
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/barrier/barrier_knomial.c
  src/components/tl/ucp/bcast/bcast_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_coll.h
  src/core/ucc_coll.c
  src/core/ucc_constructor.c
  src/core/ucc_global_opts.c
  src/core/ucc_global_opts.h
  src/core/ucc_mc.c
  src/utils/profile/ucc_profile.c
  src/utils/profile/ucc_profile.h
  src/utils/profile/ucc_profile_core.h
  src/utils/profile/ucc_profile_off.h
  src/utils/profile/ucc_profile_on.h
  src/utils/ucc_compiler_def.h
  src/utils/ucc_parser.h
  test/gtest/common/test_obj_size.cc
Labels: Ready-for-Review

#227 CORE: call task complete for schedule
  src/schedule/ucc_schedule.c
Labels: Ready-for-Review

#224 MC/CUDA: fp16 reduce
  src/components/mc/cuda/kernel/mc_cuda_reduce.cu
  src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
  src/components/mc/cuda/kernel/mc_cuda_reduce_ops.h
Labels: Ready-for-Review

#231 v0.1.x CORE: call task complete for schedule
  src/schedule/ucc_schedule.c
Labels: Ready-for-Review, Target: v0.1.x

#232 v0.1.x MC/CUDA: decrease getAddressRange log level
  src/components/mc/cuda/mc_cuda.c
Labels: Ready-for-Review, Target: v0.1.x

#230 DOCS: fixing doxygen
  Makefile.am
  src/ucc/api/ucc.h
Labels: Ready-for-Review, Target: v0.1.x

#236 Update to readme to include Open MPI compile/install instructions
  README.md
Labels: Ready-for-Review

#228 Topic/addr exchange at ctx create
  src/components/base/ucc_base_iface.h
  src/components/cl/basic/cl_basic_team.c
  src/components/cl/ucc_cl.c
  src/components/cl/ucc_cl.h
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/nccl/tl_nccl_team.c
  src/components/tl/ucc_tl.c
  src/components/tl/ucc_tl.h
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/allgather/allgather_knomial.c
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allgatherv/allgatherv_ring.c
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/barrier/barrier_knomial.c
  src/components/tl/ucp/bcast/bcast_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_addr.c
  src/components/tl/ucp/tl_ucp_addr.h
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_coll.h
  src/components/tl/ucp/tl_ucp_ep.c
  src/components/tl/ucp/tl_ucp_ep.h
  src/components/tl/ucp/tl_ucp_ep_hash.h
  src/components/tl/ucp/tl_ucp_team.c
  src/core/ucc_context.c
  src/core/ucc_context.h
  src/core/ucc_team.c
  src/core/ucc_team.h
  src/ucc/api/ucc.h
  src/utils/ucc_atomic.h
  src/utils/ucc_coll_utils.c
  src/utils/ucc_coll_utils.h
  src/utils/ucc_proc_info.c
  src/utils/ucc_proc_info.h
  test/gtest/Makefile.am
  test/gtest/common/test_ucc.cc
  test/gtest/common/test_ucc.h
  test/gtest/core/test_context.cc
  test/gtest/core/test_team.cc
  test/gtest/utils/test_ep_map.cc
Labels: Ready-for-Review

#238 MC/CUDA: init stream on demand
  src/components/mc/cuda/kernel/mc_cuda_reduce.cu
  src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
Labels: Ready-for-Review, Target: v0.1.x, bug

#242 MC/CUDA: uninit warn build fix
  src/components/mc/cuda/mc_cuda.h
Labels: Ready-for-Review
