Repository openucx/ucc, pull requests merged in 2022-01, with the labels that each got.

#345 TOOLS: add reduce_scatter to perftest
  tools/perf/Makefile.am
  tools/perf/ucc_pt_benchmark.cc
  tools/perf/ucc_pt_coll.h
  tools/perf/ucc_pt_coll_allgather.cc
  tools/perf/ucc_pt_coll_reduce_scatter.cc
  tools/perf/ucc_pt_config.cc
Labels: Ready-for-Review

#379 DOCS: Updating NEWS
  NEWS
Labels: Ready-for-Review

#380 DOCS: fix docs build
  .github/workflows/docs.yaml
  config/m4/check_tls.m4
  configure.ac
  src/components/tl/ucp/configure.m4
  src/ucc/api/ucc.h
Labels: bug, documentation, Ready-for-Review

#381 BUILD: fix autogen for non bash shell
  autogen.sh
Labels: Ready-for-Review

#383 TL/UCP: fix allgather dt check
  src/components/tl/ucp/allgather/allgather.c
Labels: bug, Ready-for-Review

#385 TL/UCP: fix allgather dt check - v1.0
  src/components/tl/ucp/allgather/allgather.c
Labels: Ready-for-Review, v1.0.0

#336 TL/CUDA: implement tl cuda
  config/m4/configure.m4
  src/Makefile.am
  src/components/tl/cuda/Makefile.am
  src/components/tl/cuda/alltoall/alltoall.c
  src/components/tl/cuda/alltoall/alltoall.h
  src/components/tl/cuda/alltoall/alltoall_ce.c
  src/components/tl/cuda/configure.m4
  src/components/tl/cuda/tl_cuda.c
  src/components/tl/cuda/tl_cuda.h
  src/components/tl/cuda/tl_cuda_cache.c
  src/components/tl/cuda/tl_cuda_cache.h
  src/components/tl/cuda/tl_cuda_coll.c
  src/components/tl/cuda/tl_cuda_coll.h
  src/components/tl/cuda/tl_cuda_context.c
  src/components/tl/cuda/tl_cuda_ep_hash.h
  src/components/tl/cuda/tl_cuda_lib.c
  src/components/tl/cuda/tl_cuda_team.c
  src/components/tl/cuda/tl_cuda_topo.c
  src/components/tl/cuda/tl_cuda_topo.h
  src/utils/ucc_math.h
  src/utils/ucc_sys.c
  src/utils/ucc_sys.h
  test/mpi/main.cc
  test/mpi/test_allgather.cc
  test/mpi/test_allgatherv.cc
  test/mpi/test_allreduce.cc
  test/mpi/test_alltoall.cc
  test/mpi/test_alltoallv.cc
  test/mpi/test_barrier.cc
  test/mpi/test_bcast.cc
  test/mpi/test_case.cc
  test/mpi/test_mpi.cc
  test/mpi/test_mpi.h
  test/mpi/test_reduce.cc
  test/mpi/test_reduce_scatter.cc
Labels: Ready-for-Review

#382 BUILD: fixes build with intel mpi
  config/m4/mpi.m4
  src/components/tl/sharp/tl_sharp_coll.c
  src/components/tl/ucp/tl_ucp_team.c
  test/mpi/test_mpi.cc
  tools/perf/ucc_pt_bootstrap_mpi.cc
Labels: Ready-for-Review

#386 DOCS: Adding Authors
  AUTHORS
Labels: Ready-for-Review

#389 DOCS: Adding Authors (#386)
  AUTHORS
Labels: Ready-for-Review, Target v1.0.x

#388 TEST: mpi test fixes
  test/mpi/test_allgather.cc
  test/mpi/test_allgatherv.cc
  test/mpi/test_allreduce.cc
  test/mpi/test_alltoall.cc
  test/mpi/test_alltoallv.cc
  test/mpi/test_barrier.cc
  test/mpi/test_bcast.cc
  test/mpi/test_case.cc
  test/mpi/test_mpi.h
  test/mpi/test_reduce.cc
  test/mpi/test_reduce_scatter.cc
Labels: Ready-for-Review

#374 TEST/GTEST: adds onesided alltoall test
  src/components/tl/ucp/alltoall/alltoall_onesided.c
  src/ucc/api/ucc.h
  test/gtest/common/test_ucc.cc
  test/gtest/common/test_ucc.h
  test/gtest/core/test_alltoall.cc
  test/gtest/core/test_context.cc
Labels: Ready-for-Review, Target v1.0.x

#390 CL/BASIC score fix
  src/coll_score/ucc_coll_score.c
  src/coll_score/ucc_coll_score.h
  src/coll_score/ucc_coll_score_map.c
  src/components/cl/basic/cl_basic_team.c
  src/core/ucc_coll.c
  src/core/ucc_team.c
  src/schedule/ucc_schedule.h
  src/utils/ucc_coll_utils.c
  src/utils/ucc_coll_utils.h
  src/utils/ucc_log.h
  src/utils/ucc_string.c
  src/utils/ucc_string.h
Labels: Ready-for-Review

#387 TL/CUDA: use nvml to detect topology
  config/m4/cuda.m4
  src/components/tl/cuda/Makefile.am
  src/components/tl/cuda/alltoall/alltoall_ce.c
  src/components/tl/cuda/tl_cuda.h
  src/components/tl/cuda/tl_cuda_common.h
  src/components/tl/cuda/tl_cuda_context.c
  src/components/tl/cuda/tl_cuda_team.c
  src/components/tl/cuda/tl_cuda_team_topo.c
  src/components/tl/cuda/tl_cuda_team_topo.h
  src/components/tl/cuda/tl_cuda_topo.c
  src/components/tl/cuda/tl_cuda_topo.h
  test/gtest/common/test_ucc.cc
Labels: Ready-for-Review

#375 TEST/MPI: adds onesided alltoall test
  test/mpi/main.cc
  test/mpi/test_alltoall.cc
  test/mpi/test_case.cc
  test/mpi/test_mpi.cc
  test/mpi/test_mpi.h
Labels: Ready-for-Review, Target v1.0.x

#394 TL/UCP: enable UCX active messages
  src/components/tl/ucp/tl_ucp_context.c
Labels: Ready-for-Review

#403 CORE: clarify ctx_cfg_modify semantics
  src/ucc/api/ucc.h
Labels: Ready-for-Review

#408 CORE: clarify ctx_cfg_modify semantics (#403)
  src/ucc/api/ucc.h
Labels: Ready-for-Review

#398 Implement TL context config modify
  src/components/base/ucc_base_iface.c
  src/components/base/ucc_base_iface.h
  src/components/cl/basic/cl_basic_context.c
  src/components/cl/basic/cl_basic_team.c
  src/components/cl/hier/cl_hier_context.c
  src/components/cl/hier/cl_hier_team.c
  src/components/cl/ucc_cl.c
  src/components/cl/ucc_cl.h
  src/components/tl/cuda/tl_cuda_context.c
  src/components/tl/cuda/tl_cuda_team.c
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/nccl/tl_nccl_team.c
  src/components/tl/sharp/tl_sharp_context.c
  src/components/tl/sharp/tl_sharp_team.c
  src/components/tl/ucc_tl.c
  src/components/tl/ucc_tl.h
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_team.c
  src/core/ucc_context.c
  src/core/ucc_context.h
  src/core/ucc_lib.c
  test/gtest/core/test_context_config.cc
Labels: Ready-for-Review

#405 TL/CUDA: store device type in topo graph
  src/components/tl/cuda/tl_cuda_topo.c
  src/components/tl/cuda/tl_cuda_topo.h
Labels: Ready-for-Review
