Repository openucx/ucc, pull requests merged in 2022-07, with the labels that each got.

#557 TL/UCP: fix executor status check
  src/components/tl/ucp/tl_ucp_coll.h
Labels: Ready-for-Review

#554 DOCS: fix ucc.h inline doc
  src/ucc/api/ucc.h
Labels: Ready-for-Review

#551 TL/RCCL and TL/NCCL: move event_destroy call
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/rccl/tl_rccl_coll.c
Labels: Ready-for-Review

#562 TL/SELF: fix linter warnings
  src/components/tl/self/tl_self_context.c
Labels: Ready-for-Review

#546 TL/CUDA: check cuda device in coll init
  src/components/tl/cuda/tl_cuda_coll.c
  test/mpi/main.cc
  test/mpi/test_mpi.cc
Labels: Ready-for-Review

#563 CORE: fix spelling
  src/core/ucc_context.h
  src/core/ucc_team.c
  src/ucc/api/ucc.h
Labels: Ready-for-Review

#544 TL/CUDA: multicopy allgatherv
  src/components/ec/base/ucc_ec_base.h
  src/components/ec/cpu/ec_cpu.c
  src/components/ec/cuda/ec_cuda_executor_interruptible.c
  src/components/ec/cuda/kernel/ec_cuda_executor.cu
  src/components/tl/cuda/allgatherv/allgatherv_ring.c
  src/components/tl/cuda/alltoallv/alltoallv_ce.c
  src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
  src/components/tl/cuda/tl_cuda.c
  src/components/tl/cuda/tl_cuda.h
  src/components/tl/cuda/tl_cuda_lib.c
  src/components/tl/cuda/tl_cuda_team_topo.c
  src/utils/ucc_coll_utils.h
Labels: Ready-for-Review, Target v1.1.0

#555 BUILD: return error for not implemented functions
  src/core/ucc_coll.c
  src/core/ucc_team.c
  src/ucc/api/ucc.h
Labels: Ready-for-Review, API, Target v1.1.0

#561 TL/CUDA: allgather(v) linear alg
  src/components/tl/cuda/Makefile.am
  src/components/tl/cuda/allgather/allgather.c
  src/components/tl/cuda/allgather/allgather.h
  src/components/tl/cuda/allgather/allgather_linear.c
  src/components/tl/cuda/allgather/allgather_ring.c
  src/components/tl/cuda/allgatherv/allgatherv.c
  src/components/tl/cuda/allgatherv/allgatherv.h
  src/components/tl/cuda/allgatherv/allgatherv_linear.c
  src/components/tl/cuda/allgatherv/allgatherv_ring.c
  src/components/tl/cuda/tl_cuda.c
  src/components/tl/cuda/tl_cuda.h
  src/components/tl/cuda/tl_cuda_coll.c
  src/components/tl/cuda/tl_cuda_coll.h
  src/components/tl/cuda/tl_cuda_team.c
Labels: Ready-for-Review, Target v1.1.0

#565 MC/CUDA: add uint16(32,64) support in reduce
  src/components/mc/cuda/kernel/mc_cuda_reduce.cu
  src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
  test/gtest/core/test_mc_reduce.h
  test/mpi/main.cc
  test/mpi/test_mpi.cc
Labels: Ready-for-Review

#540 TEST: skip gtest team_size=1 w/o tl/self
  test/gtest/common/test_ucc.cc
  test/gtest/common/test_ucc.h
  test/gtest/core/test_team.cc
Labels: Ready-for-Review

#571 CORE: option to disable cfg file
  src/core/ucc_constructor.c
  src/core/ucc_global_opts.c
Labels: Ready-for-Review, Target v1.1.0

#580 TEST/MPI: use dedicated comm per ucc team
  test/mpi/mpi_util.cc
  test/mpi/test_mpi.cc
Labels: Ready-for-Review

#583 TEST/MPI: don't call comm_split from set_gpu_dev
  test/mpi/main.cc
  test/mpi/test_mpi.cc
  test/mpi/test_mpi.h
Labels: Ready-for-Review

#582 TL/NCCL: allgatherv send dtype check fix
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_team.c
Labels: Ready-for-Review
