Repository openucx/ucc, pull requests merged in 2022-04, with the labels that each got.

#449 TL/UCP: reduce_kn avg pre op fix
  src/components/tl/ucp/reduce/reduce.c
  src/components/tl/ucp/reduce/reduce_knomial.c
Labels: Ready-for-Review, Target v1.0.x

#451 TL/NCCL: check stream capturing
  src/components/tl/nccl/tl_nccl_coll.c
Labels: Ready-for-Review

#452 CORE: add ucc task internal status (#441)
  src/components/tl/nccl/allgatherv/allgatherv.c
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_context.c
  src/components/tl/sharp/tl_sharp_coll.c
  src/components/tl/ucp/allgather/allgather.c
  src/components/tl/ucp/allgather/allgather.h
  src/components/tl/ucp/allgather/allgather_knomial.c
  src/components/tl/ucp/allgather/allgather_ring.c
  src/components/tl/ucp/allgatherv/allgatherv.c
  src/components/tl/ucp/allgatherv/allgatherv_ring.c
  src/components/tl/ucp/allreduce/allreduce.h
  src/components/tl/ucp/allreduce/allreduce_knomial.c
  src/components/tl/ucp/alltoall/alltoall.c
  src/components/tl/ucp/alltoall/alltoall_onesided.c
  src/components/tl/ucp/alltoall/alltoall_pairwise.c
  src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
  src/components/tl/ucp/barrier/barrier.c
  src/components/tl/ucp/barrier/barrier_knomial.c
  src/components/tl/ucp/bcast/bcast.c
  src/components/tl/ucp/bcast/bcast.h
  src/components/tl/ucp/bcast/bcast_knomial.c
  src/components/tl/ucp/reduce/reduce.c
  src/components/tl/ucp/reduce/reduce.h
  src/components/tl/ucp/reduce/reduce_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/scatter/scatter_knomial.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_coll.h
  src/components/tl/ucp/tl_ucp_sendrecv.h
  src/core/ucc_coll.c
  src/core/ucc_progress_queue.h
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/schedule/ucc_schedule_pipelined.c
  src/ucc/api/ucc.h
  test/gtest/common/test_ucc.cc
Labels: Ready-for-Review, Target v1.0.x

#455 TL/UCP: add error return in allreduce kn
  src/components/tl/ucp/allreduce/allreduce_knomial.c
Labels: Ready-for-Review

#454 TL/UCP: reduce_kn avg pre op fix (#449)
  src/components/tl/ucp/reduce/reduce.c
  src/components/tl/ucp/reduce/reduce_knomial.c
Labels: Ready-for-Review

#428 CL/HIER: split rail allreduce
  .ci/scripts/run_tests_ucc_mpi.sh
  src/coll_score/ucc_coll_score.c
  src/components/cl/hier/Makefile.am
  src/components/cl/hier/allreduce/allreduce.c
  src/components/cl/hier/allreduce/allreduce.h
  src/components/cl/hier/allreduce/allreduce_rab.c
  src/components/cl/hier/allreduce/allreduce_split_rail.c
  src/components/cl/hier/alltoallv/alltoallv.c
  src/components/cl/hier/barrier/barrier.c
  src/components/cl/hier/cl_hier.c
  src/components/cl/hier/cl_hier.h
  src/components/cl/hier/cl_hier_coll.c
  src/components/cl/hier/cl_hier_coll.h
  src/components/cl/hier/cl_hier_team.c
  src/components/tl/nccl/allgatherv/allgatherv.h
  src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
  src/components/tl/ucp/bcast/bcast_sag_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c
  src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c
  src/components/topo/ucc_sbgp.c
  src/components/topo/ucc_topo.h
  src/core/ucc_team.h
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/schedule/ucc_schedule_pipelined.c
Labels: Ready-for-Review

#458 CORE: suppress warn from tl ctx fail
  src/components/tl/sharp/tl_sharp_context.c
  src/core/ucc_context.c
  src/core/ucc_lib.c
  src/core/ucc_lib.h
Labels: Ready-for-Review

#457 TEST: mpi barrier progress
  test/mpi/test_barrier.cc
Labels: bug, Ready-for-Review

#453 TL/UCP: correct address parsing
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_ep.c
  src/components/tl/ucp/tl_ucp_ep.h
  src/components/tl/ucp/tl_ucp_sendrecv.h
Labels: Ready-for-Review

#459 BUILD: add cuda arch flag
  config/m4/cuda.m4
Labels: Ready-for-Review

#464 TL/CUDA: find better proxies for alltoall
  src/components/tl/cuda/tl_cuda_team_topo.c
Labels: Ready-for-Review

#463 Multithreading fixes
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/schedule/ucc_schedule_pipelined.c
  src/schedule/ucc_schedule_pipelined.h
Labels: Ready-for-Review

#469 UTIL: ep_map_nested
  src/utils/ucc_coll_utils.c
  src/utils/ucc_coll_utils.h
  test/gtest/utils/test_ep_map.cc
Labels: Ready-for-Review

#470 V1.0.x Multithreading fixes (#463)
  src/schedule/ucc_schedule.c
  src/schedule/ucc_schedule.h
  src/schedule/ucc_schedule_pipelined.c
  src/schedule/ucc_schedule_pipelined.h
Labels: Ready-for-Review, Target v1.0.x

#471 SCHEDULE: remove unused fn
  src/schedule/ucc_schedule.h
Labels: Ready-for-Review

#483 TEST: fix leak in test nested ep map
  test/gtest/utils/test_ep_map.cc
Labels: Ready-for-Review

#465 TEST: enable tl cuda alltoallv tests
  test/mpi/test_alltoallv.cc
  tools/perf/ucc_pt_coll_alltoallv.cc
Labels: Ready-for-Review

#473 TL/NCCL: add gatherv
  src/components/tl/nccl/tl_nccl.h
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_coll.h
  src/components/tl/nccl/tl_nccl_team.c
  test/mpi/Makefile.am
  test/mpi/main.cc
  test/mpi/test_case.cc
  test/mpi/test_gatherv.cc
  test/mpi/test_mpi.h
Labels: Ready-for-Review

#468 Fix multi-threading of ucc_test_mpi
  .ci/scripts/run_tests_ucc_mpi.sh
  src/components/ec/cuda/ec_cuda.c
  src/components/ec/cuda/ec_cuda.h
  src/components/mc/cuda/mc_cuda.c
  src/components/mc/cuda/mc_cuda.h
  src/utils/ucc_atomic.h
  test/mpi/main.cc
  test/mpi/test_mpi.cc
  test/mpi/test_mpi.h
Labels: Ready-for-Review

#484 TOOLS: fix peftest timer
  tools/perf/ucc_pt_benchmark.cc
  tools/perf/ucc_pt_benchmark.h
  tools/perf/ucc_pt_comm.cc
  tools/perf/ucc_pt_comm.h
Labels: Ready-for-Review

#485 CL/HIER: inplace alltoall fallback
  src/components/cl/hier/alltoall/alltoall.c
  src/components/cl/hier/alltoallv/alltoallv.c
Labels: Ready-for-Review

#472 TL/NCCL: add scatter
  src/components/tl/nccl/tl_nccl.h
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_coll.h
  src/components/tl/nccl/tl_nccl_team.c
  test/mpi/Makefile.am
  test/mpi/main.cc
  test/mpi/test_case.cc
  test/mpi/test_mpi.h
  test/mpi/test_scatter.cc
Labels: Ready-for-Review

#481 BUILD: print cuda archs after config
  config/m4/cuda.m4
  configure.ac
Labels: Ready-for-Review

#474 TL/NCCL: add scatterv
  src/components/tl/nccl/tl_nccl.h
  src/components/tl/nccl/tl_nccl_coll.c
  src/components/tl/nccl/tl_nccl_coll.h
  src/components/tl/nccl/tl_nccl_team.c
  test/mpi/Makefile.am
  test/mpi/main.cc
  test/mpi/test_case.cc
  test/mpi/test_mpi.h
  test/mpi/test_scatterv.cc
Labels: Ready-for-Review

#488 TOOLS: use memunits in perftest
  tools/perf/ucc_pt_config.cc
Labels: Ready-for-Review

#480 BUILD: take libucm from user defined dir
  config/m4/ucx.m4
  test/gtest/Makefile.am
  test/mpi/Makefile.am
  tools/info/Makefile.am
  tools/perf/Makefile.am
Labels: Ready-for-Review

#491 TEST: fix verbose option
  test/mpi/main.cc
Labels: Ready-for-Review

#490 TL/CUDA: fix zero size rs and ag
  src/components/tl/cuda/allgatherv/allgatherv_ring.c
  src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
Labels: Ready-for-Review

#467 CL/HIER: enable alltoall(v)
  src/components/cl/hier/alltoallv/alltoallv.c
  src/components/cl/hier/cl_hier.h
Labels: Ready-for-Review
