Repository openucx/ucc, pull requests merged in 2024-02, with the labels that each got.

#910 TL/MLX5: ad librdmacm linkage (#905)
  src/components/tl/mlx5/Makefile.am
Labels: Target v1.3.0

#914 BUILD: fix GPU arch flags in amdclang build
  cuda_lt.sh
Labels: Ready-for-Review, Target v1.3.0

#915 TL/UCP: adjust barrier radix
  src/components/tl/ucp/tl_ucp.c
Labels: Ready-for-Review

#921 TL/MLX5: disable mcast init
  src/components/tl/mlx5/tl_mlx5_context.c
  src/components/tl/mlx5/tl_mlx5_team.c
Labels: Ready-for-Review

#919 CL/HIER: check number of TLs per SBGP
  src/components/cl/hier/cl_hier_team.c
  src/components/ec/cuda/ec_cuda.c
  src/components/mc/cuda/mc_cuda.c
  test/mpi/main.cc
Labels: Ready-for-Review

#922 TL/MLX5: enhance error handling in mlx5 ctx
  src/components/tl/mlx5/tl_mlx5_context.c
Labels: Ready-for-Review

#920 API: remove duplicate get_version_string
  src/ucc/api/ucc.h
Labels: Ready-for-Review

#923 CL/HIER: change score only for supported colls
  src/coll_score/ucc_coll_score.c
  src/coll_score/ucc_coll_score.h
  src/coll_score/ucc_coll_score_map.c
  src/components/cl/hier/cl_hier.h
  src/components/cl/hier/cl_hier_team.c
Labels: Ready-for-Review

#924 CORE: add progress throttle
  src/components/tl/ucp/bcast/bcast_dbt.c
  src/components/tl/ucp/reduce/reduce_dbt.c
  src/core/ucc_context.c
  src/core/ucc_context.h
  src/core/ucc_progress_queue.h
  src/core/ucc_progress_queue_mt.c
  src/core/ucc_progress_queue_st.c
Labels: Ready-for-Review

#898 TL/UCP: Allgather Bruck algorithm
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/allgather/allgather.c
  src/components/tl/ucp/allgather/allgather.h
  src/components/tl/ucp/allgather/allgather_bruck.c
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_coll.h
  test/gtest/coll/test_allgather.cc
Labels: Ready-for-Review

#930 EC/CPU: Fix int8 auto-vectorization with gcc 4.8.2
  src/components/ec/cpu/ec_cpu.c
  src/components/ec/cpu/ec_cpu.h
  src/components/ec/cpu/ec_cpu_reduce.c
Labels: Ready-for-Review

#934 UTIL: add parser doc V1.3.x
  config/m4/ucx.m4
  src/utils/ucc_parser.h
Labels: Target v1.3.0

#933 API: remove duplicate get_version_string V1.3.x
  src/ucc/api/ucc.h
Labels: Target v1.3.0
