Repository openucx/ucc, pull requests merged in 2025-07, with the labels that each got.

#1144 TL/CUDA: NVLink SHARP (NVLS) Reduce Scatter
  config/m4/nvls.m4
  configure.ac
  src/components/tl/cuda/Makefile.am
  src/components/tl/cuda/configure.m4
  src/components/tl/cuda/kernels/Makefile.am
  src/components/tl/cuda/kernels/reduce_scatter_kernel.cu
  src/components/tl/cuda/reduce_scatter/reduce_scatter.c
  src/components/tl/cuda/reduce_scatter/reduce_scatter.h
  src/components/tl/cuda/reduce_scatter/reduce_scatter_nvls.c
  src/components/tl/cuda/tl_cuda.h
  src/components/tl/cuda/tl_cuda_coll.c
  src/components/tl/cuda/tl_cuda_nvls.c
  src/components/tl/cuda/tl_cuda_nvls.h
  src/components/tl/cuda/tl_cuda_team.c
Labels: Ready-for-Review

#1151 TOOLS/UCC_PERFTEST: Adding missing progress calls
  tools/perf/ucc_pt_comm.cc
Labels: Ready-for-Review

#1137 TL/CUDA: Topology Cache
  src/components/tl/cuda/tl_cuda.c
  src/components/tl/cuda/tl_cuda.h
  src/components/tl/cuda/tl_cuda_context.c
  src/components/tl/cuda/tl_cuda_lib.c
Labels: Ready-for-Review, Code-Review-Completed

#1143 BUILD: update cuda arch
  config/m4/compiler.m4
  config/m4/cuda.m4
  configure.ac
Labels: Ready-for-Review

#1152 BUILD: fix coverity issues
  src/components/cl/hier/allgatherv/allgatherv.c
  src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
  src/components/tl/mlx5/tl_mlx5_team.c
  src/components/tl/ucp/alltoall/alltoall_bruck.c
  src/components/tl/ucp/gather/gather_knomial.c
  src/core/ucc_context.c
  src/utils/ucc_coll_utils.c
Labels: Ready-for-Review

#1147 TOOLS: add perftest generator
  tools/perf/Makefile.am
  tools/perf/generator/examples/alltoallv_16.ptini
  tools/perf/generator/examples/alltoallv_4.ptini
  tools/perf/generator/ucc_pt_generator.h
  tools/perf/generator/ucc_pt_generator_exp.cc
  tools/perf/generator/ucc_pt_generator_file.cc
  tools/perf/ucc_pt_benchmark.cc
  tools/perf/ucc_pt_benchmark.h
  tools/perf/ucc_pt_coll.h
  tools/perf/ucc_pt_coll_allgather.cc
  tools/perf/ucc_pt_coll_allgatherv.cc
  tools/perf/ucc_pt_coll_allreduce.cc
  tools/perf/ucc_pt_coll_alltoall.cc
  tools/perf/ucc_pt_coll_alltoallv.cc
  tools/perf/ucc_pt_coll_barrier.cc
  tools/perf/ucc_pt_coll_bcast.cc
  tools/perf/ucc_pt_coll_gather.cc
  tools/perf/ucc_pt_coll_gatherv.cc
  tools/perf/ucc_pt_coll_reduce.cc
  tools/perf/ucc_pt_coll_reduce_scatter.cc
  tools/perf/ucc_pt_coll_reduce_scatterv.cc
  tools/perf/ucc_pt_coll_scatter.cc
  tools/perf/ucc_pt_coll_scatterv.cc
  tools/perf/ucc_pt_comm.cc
  tools/perf/ucc_pt_config.cc
  tools/perf/ucc_pt_config.h
  tools/perf/ucc_pt_cuda.cc
  tools/perf/ucc_pt_cuda.h
  tools/perf/ucc_pt_op_memcpy.cc
  tools/perf/ucc_pt_op_reduce.cc
  tools/perf/ucc_pt_op_reduce_strided.cc
Labels: Code-Review-Completed

#1100 TEST: add buffers for onesided tests
  test/mpi/test_mpi.cc
Labels: Ready-for-Review

#1161 TL/MLX5: do reliability-init after mcast setup
  src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_service_coll.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_service_coll.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
  src/components/tl/mlx5/tl_mlx5.h
Labels: Ready-for-Review
