Repository openucx/ucc, pull requests merged in 2025-04, with the labels that each got.

#1079 TL/UCP: disable proto that need memory type copy
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_context.c
Labels: Ready-for-Review

#1106 TEST: build sm70 only in CI
  .ci/scripts/build_ucc.sh
  .ci/scripts/coverity.sh
Labels: Ready-for-Review

#1085 TL/MLX5: Stabilize staging-based AG and Add zcopy AG
  src/components/tl/mlx5/Makefile.am
  src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_allgather.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_service_coll.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
  src/components/tl/mlx5/tl_mlx5.c
  src/components/tl/mlx5/tl_mlx5.h
  src/components/tl/mlx5/tl_mlx5_coll.c
  src/components/tl/mlx5/tl_mlx5_team.c
Labels: Ready-for-Review, Code-Review-Completed

#1091 TOOLS: Add error handling for benchmark run
  tools/perf/ucc_perftest.cc
Labels: Ready-for-Review

#1058 TL/UCP: add reduce srg knomial
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/gather/gather_knomial.c
  src/components/tl/ucp/reduce/reduce.c
  src/components/tl/ucp/reduce/reduce.h
  src/components/tl/ucp/reduce/reduce_srg_knomial.c
  src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_coll.h
  test/gtest/Makefile.am
  test/gtest/coll/test_reduce.cc
Labels: Ready-for-Review, Code-Review-Completed

#1095 TL/UCP: Knomial allgather default for cuda mem
  src/components/tl/ucp/allgather/allgather.c
  src/components/tl/ucp/allgather/allgather.h
  src/components/tl/ucp/tl_ucp_team.c
  src/components/topo/ucc_topo.h
  src/utils/ucc_coll_utils.c
Labels: Code-Review-Completed

#1112 TL/SHARP: enable AG and RS after 16k
  src/components/tl/sharp/tl_sharp_coll.c
  src/components/tl/sharp/tl_sharp_coll.h
  src/components/tl/sharp/tl_sharp_team.c
Labels: Ready-for-Review

#1108 TEST: check device version in transpose test
  test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc
Labels: Ready-for-Review

#1109 TL/UCP: Split single and multithreaded send/receive
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_coll.c
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_sendrecv.h
Labels: enhancement

#1119 DOCS: Update NEWS for 1.4
  AUTHORS
  NEWS
Labels: Ready-for-Review

#1118 TL/MLX5: add cuda support for zcopy mcast
  src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_allgather.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
  src/components/tl/mlx5/tl_mlx5.c
Labels: Ready-for-Review

#1121 BUILD: bump version to v1.5
  configure.ac
Labels: Ready-for-Review

#1104 CORE: enhance error log in collective init
  src/components/tl/ucp/allreduce/allreduce.c
  src/core/ucc_coll.c
  src/utils/ucc_coll_utils.h
Labels: Ready-for-Review

#1113 TL/MLX5: ctx global status check
  src/components/tl/mlx5/tl_mlx5_context.c
Labels: Ready-for-Review
