Repository openucx/ucc, pull requests merged in 2025-03, with the labels that each got.

#1077 TL/UCP: add local copy option
  src/components/tl/ucp/Makefile.am
  src/components/tl/ucp/allgather/allgather_knomial.c
  src/components/tl/ucp/tl_ucp.c
  src/components/tl/ucp/tl_ucp.h
  src/components/tl/ucp/tl_ucp_coll.h
  src/components/tl/ucp/tl_ucp_context.c
  src/components/tl/ucp/tl_ucp_copy.c
  src/components/tl/ucp/tl_ucp_copy.h
Labels: Ready-for-Review

#1081 TL/SHARP: add support for allgather
  config/m4/sharp.m4
  src/components/tl/sharp/tl_sharp.h
  src/components/tl/sharp/tl_sharp_coll.c
  src/components/tl/sharp/tl_sharp_coll.h
  src/components/tl/sharp/tl_sharp_team.c
Labels: Ready-for-Review

#1084 TL/SHARP: enable reduce-scatter only when SAT is enabled.
  src/components/tl/sharp/tl_sharp.c
  src/components/tl/sharp/tl_sharp.h
  src/components/tl/sharp/tl_sharp_coll.c
  src/components/tl/sharp/tl_sharp_context.c
  src/components/tl/sharp/tl_sharp_team.c
Labels: Ready-for-Review

#1094 GTEST: fix UMR QP create config set
  test/gtest/tl/mlx5/test_tl_mlx5_qps.h
Labels: Ready-for-Review

#1050 CL/HIER: Add allgatherv
  src/components/cl/hier/Makefile.am
  src/components/cl/hier/allgatherv/allgatherv.c
  src/components/cl/hier/allgatherv/allgatherv.h
  src/components/cl/hier/allgatherv/unpack.c
  src/components/cl/hier/allgatherv/unpack.h
  src/components/cl/hier/cl_hier.c
  src/components/cl/hier/cl_hier.h
  src/components/cl/hier/cl_hier_coll.c
  src/components/cl/hier/cl_hier_coll.h
  src/components/cl/hier/cl_hier_team.c
  src/components/topo/ucc_sbgp.c
  src/components/topo/ucc_sbgp.h
  src/utils/ucc_coll_utils.h
  test/gtest/coll/test_allgatherv.cc
  test/gtest/common/test_ucc.cc
  test/gtest/common/test_ucc.h
Labels: Ready-for-Review, Code-Review-Completed

#1073 UTIL: fix names array memory leak
  src/utils/ucc_parser.c
Labels: Ready-for-Review

#1075 TL/MLX5: complete the multi mcast group design
  src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
  src/components/tl/mlx5/tl_mlx5.c
  src/components/tl/mlx5/tl_mlx5.h
Labels: Ready-for-Review

#1062 TL/MLX5: add ctx option to disable a2a
  src/components/tl/mlx5/alltoall/alltoall_coll.c
  src/components/tl/mlx5/tl_mlx5.c
  src/components/tl/mlx5/tl_mlx5.h
  src/components/tl/mlx5/tl_mlx5_context.c
  src/components/tl/mlx5/tl_mlx5_dm.c
  src/components/tl/mlx5/tl_mlx5_team.c
Labels: Ready-for-Review, Code-Review-Completed

#1023 TL/MLX5: add gtest for mcast
  test/gtest/coll/test_bcast.cc
Labels: Ready-for-Review

#1089 TL/UCP: fix in-place for service AG
  src/components/tl/ucp/tl_ucp_service_coll.c
Labels: Ready-for-Review

#1097 CORE: destroy service team last
  src/core/ucc_context.c
Labels: Ready-for-Review

#1102 TL/MLX5: gdr checks and support for CUDA mt
  src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
  src/components/tl/mlx5/tl_mlx5.h
  src/components/tl/mlx5/tl_mlx5_context.c
  src/components/tl/mlx5/tl_mlx5_team.c
Labels: Ready-for-Review

#1093 EC/CUDA: batch memory operations
  src/components/ec/cuda/ec_cuda_executor_persistent_wait.c
Labels: enhancement, Code-Review-Completed

#1067 TL/MLX5: a2a various optimizations
  src/components/tl/mlx5/alltoall/alltoall_coll.c
  src/components/tl/mlx5/alltoall/alltoall_mkeys.c
  src/components/tl/mlx5/tl_mlx5.c
  src/components/tl/mlx5/tl_mlx5.h
  src/components/tl/mlx5/tl_mlx5_coll.h
  src/components/tl/mlx5/tl_mlx5_dm.c
  src/components/tl/mlx5/tl_mlx5_wqe.c
  src/utils/ucc_math.h
  test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc
Labels: Ready-for-Review, Code-Review-Completed
